{{- if eq .Value.coder.secretStore.enable "true" }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Value.coder.namespace }}
  namespace: {{ .Value.coder.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Value.coder.secretStore.region }}
      role: {{ .Value.coder.secretStore.role }}
